apiVersion: v1
kind: Service
metadata:
  name: api-test
  namespace: production
  labels:
    app: api-test
    tier: api
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: api-port
  selector:
    app: api-test
    tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
  namespace: production
spec:
  selector:
    matchLabels:
      app: api-test
      tier: api
  replicas: 4
  template:
    metadata:
      labels:
        app: api-test
        tier: api
    spec:
      containers:
        - name: api-test
          image: victormongi/api-test:IMAGE_TAG
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 80Mi
              cpu: 50m
          ports:
            - containerPort: 5000
